// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afwpzgddyzxlwidvctvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmd3B6Z2RkeXp4bHdpZHZjdHZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5NDExMjYsImV4cCI6MjA3NjUxNzEyNn0.mn25uWRyxx3_CvPKzn_HaPqY8a95MNGf6yBEdDlwyRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});